services:
  api-gateway:
    build: ./api-gateway
    env_file:
      - ./api-gateway/.env
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  
  redis:
    image: redis:7.4.0
    ports:
      - 6379:6379
  
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    